# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.0'
use_frameworks!
pod 'Funcussion', '~> 0.1.1'
pod 'OCCalculator', :path => '../OCCalculator'

target 'PodFrameworkApp' do
end

# pod 'Funcussion', :path => '../funcussion'
